// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgmptgpboryztgcmbhjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnbXB0Z3Bib3J5enRnY21iaGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjIwMTMsImV4cCI6MjA3NDAzODAxM30.jOZBEE6TMm0lPfL3xp4o243jFh0SkXTHuqUjPd236TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});